/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Inventario;

import Inventario.DetalleInventario.PanelDetalleInventario;
import Inventario.RegistrarProveedor.PanelRegistrarProveedor;
import Inventario.RellenarInventario.PanelRellenarInventario;


import java.awt.Component;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author baez_ hola 
 */
public class PanelInventario extends javax.swing.JPanel {
   // private Utils.Utils utils = new Utils.Utils();
    /**
     * Creates new form PanelInventario
     */
    
    private final String rutaBase = "src\\IMG\\";

    public PanelInventario() {
        initComponents();
        PanelDetalleInventario pdi = new PanelDetalleInventario();
        PanelRegistrarProveedor prp = new PanelRegistrarProveedor();
        PanelRellenarInventario pri = new PanelRellenarInventario(pdi);
        
        tabPaneInventario.addTab("Detalle Inventario", pdi);
        tabPaneInventario.addTab("Proveedor", prp);
        tabPaneInventario.addTab("Rellenar Inventario", pri);

    }
    
    
    public void setScaledImage(JLabel lblImage, String imageName, int width, int height) {
        String imagePath = rutaBase + imageName;
        ImageIcon img = new ImageIcon(imagePath);
        Image scaledImage = img.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        Icon icon = new ImageIcon(scaledImage);
        lblImage.setIcon(icon);
        lblImage.setAlignmentX(Component.CENTER_ALIGNMENT);
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneInventario = new Utils.MaterialTabbed();
        PanelBarBlue = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1005, 660));
        setPreferredSize(new java.awt.Dimension(1005, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPaneInventario.setForeground(java.awt.Color.white);
        tabPaneInventario.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tabPaneInventario.setPreferredSize(new java.awt.Dimension(1005, 660));
        add(tabPaneInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1005, 660));

        PanelBarBlue.setBackground(new java.awt.Color(24, 39, 72));
        PanelBarBlue.setPreferredSize(new java.awt.Dimension(1005, 40));

        javax.swing.GroupLayout PanelBarBlueLayout = new javax.swing.GroupLayout(PanelBarBlue);
        PanelBarBlue.setLayout(PanelBarBlueLayout);
        PanelBarBlueLayout.setHorizontalGroup(
            PanelBarBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1005, Short.MAX_VALUE)
        );
        PanelBarBlueLayout.setVerticalGroup(
            PanelBarBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(PanelBarBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBarBlue;
    private Utils.MaterialTabbed tabPaneInventario;
    // End of variables declaration//GEN-END:variables
}
